[package]
name = "stfl-chatter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
bytes = "1.7.2"
futures = "0.3.31"
tokio = {version = "1.40.0", features = ["full"]}
tokio-util = {version = "0.7.12", features = ["full"] }

